version: '3'

services:

  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    env_file:
      - db/mssql.env
    ports:
      - 1433:1433
    container_name: learnsqldb
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
